workspace:
  base: /go
  path: src/github.com/cjsaylor/chessbot

pipeline:
  test:
    image: cjsaylor/go-alpine-sdk:1.10
    commands:
      - go get -u golang.org/x/tools/cmd/cover
      - go test -cover $(go list ./... | grep -v /vendor/)