version: "3"

services:
  app:
    image: cjsaylor/chessbot
    environment:
      - VIRTUAL_HOST=chessbot.chris-saylor.com
    env_file: .env
    networks:
      - public-nw

networks:
  public-nw:
    external:
      name: public-nw