version: "3"

services:
  app:
    image: cjsaylor/chessbot
    environment:
      - VIRTUAL_HOST=chessbot.chris-saylor.com
    env_file: .env
    networks:
      - public-nw
    volumes:
      # Leaving the old while transitioning to a data volume
      - /var/local/chessbot:/app/data
      - db-data:/app/db

networks:
  public-nw:
    external:
      name: public-nw

volumes:
  db-data: